version: "2"
services:
  spring-backend:
    image: awzurn/spac-fusion-api
    links:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
      - 443
    networks:
      back:
        aliases:
          - local-api-fusion.docker
    environment:
      DATABASE_USER: admin
      DATABASE_PWD: admin
      DATABASE_URL: jdbc:postgresql://db:5432/spac_fusion
  db:
    image: postgres:9.5.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spac_fusion
    ports:
      - 15432:5432
    expose:
      - 5432
    networks:
      - back
networks:
  back:
    driver: bridge
